### ISSUE TITLE
Make a logo / icon for this app

### ISSUE THREAD

**Issue by Illusion47586** [Illusion47586/covid_resources-india#3]
Just make sure it is friendly with IDK, good colors maybe? Some colors I chose are [here](https://github.com/Illusion47586/covid_resources-india/blob/master/lib/core/theme/colors.dart), and the font is [manrope](https://fonts.google.com/specimen/Manrope?query=manrope).

**Comment by jameskorah** [comment]
Hello @Illusion47586,

I've tried to address this with #9. 
Let me know if you have any suggestions.
